### ISSUE TITLE
Please bump quiver dependency

### ISSUE THREAD

**Issue by jonaskello** [bwu-dart/bwu_datagrid#105]
I'm using built_collection together with bwu_datagrid:

Incompatible version constraints on quiver:
- built_collection 0.1.1 depends on version >=0.21.0
- bwu_datagrid 0.0.18 depends on version >=0.18.2 <0.19.0

**Comment by zoechi** [comment]
Will do. Thanks for reporting.

**Comment by zoechi** [comment]
Done, sorry that it took so long.
