### ISSUE TITLE
Upgrade to Polymer 1.0.x

### ISSUE THREAD

**Issue by zoechi** [bwu-dart/bwu_datagrid#120]

**Comment by Rasarts** [comment]
Hi. Can bwu_datagrid work with polymer 1.0.0-rc.15? It's will be awesome.

**Comment by zoechi** [comment]
The last Polymer version I tried with bwu_datagrid was 1.0.0-rc.5  
with the published version bwu_datagrid 0.1.0-dev.0 (listed way down at the bottom in https://pub.dartlang.org/packages/bwu_datagrid/versions)
I guess it's worth a try with Polymer rc.15. Not too many things have changed in Polymer since then AFAIK. 
If you run into problems please file a bug report. I plan to check again myself soon but I'm currently working on other things therefore I don't unless someone reports problems.

**Comment by zoechi** [comment]
Thanks for you interest in bwu_datagrid anyway :)

**Comment by Rasarts** [comment]
Very cool. I to able to try it with new version soon.  Thanks for your awesome component!

**Comment by zoechi** [comment]
I consider this to be done even though it's till `-dev.x` but Polymer itself is only RC.
