### ISSUE TITLE
Dragging column's header label triggers 'InvalidCharacterError' and stacks all columns into one.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [bwu-dart/bwu_datagrid#126]
While testing the Polymer 1 branch in FireFox 44.0.2/OSX:

Bug:
Click-and-drag any column's header label, when the mouse is released, this shows up:
**InvalidCharacterError: String contains an invalid character e05_collapsing.bootstrap.initialize.dart.js:14540:0**
![screen shot 2016-02-29 at 5 01 08 pm](https://cloud.githubusercontent.com/assets/10780925/13414262/13fa4b02-df06-11e5-910c-f3c1a4731644.png)

Then all the columns get stacked into one incoherent column, headers are gone.

SDK in use: 1.14.2

**Comment by zoechi** [comment]
similar to #87

Thanks for trying bwu_datagrid!
I'm aware of some issues with Firefox. This column reordering issue IMHO the most annoying one. I hope to find some time soon to improve here.

**Comment by tonosama-atlacatl** [comment]
NP, great DataGrid BTW!
I know....FF, we're currently scratching our heads w/some scrollbar issues in FF...
Again, many thanks for this gift to the community, there aren't that many datagrids out there that are currently being dev...

BTW, I saw your letter to github, I'm glad you at least got a reply..., It'll be nice to have custom fields on issues...specially when the project has multiple branches, etc.. :)

**Comment by hansrutstrom** [comment]
Just happened to browse through this repo and tested some of the examples out. I encountered the same re-ordering issue also with IE and Edge. Looks like a great data-grid otherwise, keep up the good work!

**Comment by zoechi** [comment]
@ruthans thanks for the feedback. Yes, there is some work to to to make it work better in other browsers than Chrome.

**Comment by zoechi** [comment]
closing as dup of #87

**Comment by zoechi** [comment]
I published a new version with a fix.
