### ISSUE TITLE
Column Headers are ~8px wider in FF/Safari

### ISSUE THREAD

**Issue by tonosama-atlacatl** [bwu-dart/bwu_datagrid#141]
I'm not sure if this is a duplicate ticket/issue. But, in FF/Safari the column headers seem to be wider than Chrome/Chromium. Removing the checkbox column has no effect.

Column headers in Chrome/Chromium:
![screen shot 2016-06-01 at 10 55 43 am](https://cloud.githubusercontent.com/assets/10780925/15720097/d50b7af8-27e7-11e6-99fb-2a9ae61510cb.png)
_Notice how the column's header width matches the column content..._

Column headers in FF/Safari:
![screen shot 2016-06-01 at 10 56 20 am](https://cloud.githubusercontent.com/assets/10780925/15720162/084cffb8-27e8-11e6-8f7f-bc0d20571696.png)
_Notice how every column is at least 8px wider._

I found this 8px discrepancy while comparing all bwu-datagrid-header-column's style attribute. In there you'll see a "width: #px" that is 8px wider.

Testing enviroment:
OSX 10.11.5
SDK: 1.15.0
Firefox: 46.0.1
Safari: 9.1.1 (11601.6.17)
Chrome: 50.0.2661.102 (64-bit)
web_components: ^0.12.0
polymer_elements: ^1.0.0-rc.8
browser: ^0.10.0
polymer: ^1.0.0-rc.16

**Comment by zoechi** [comment]
Thanks for reporting. I'll check it.

**Comment by zoechi** [comment]
Can't reproduce anymore after other changes I made recently (not yet published)
