### ISSUE TITLE
Class 'MouseEvent' has no instance getter 'which'.

### ISSUE THREAD

**Issue by andrey-zakharov** [bwu-dart/bwu_datagrid#151]
Got this when clicked on column: 
`
Uncaught Unhandled exception:
Class 'MouseEvent' has no instance getter 'which'.

NoSuchMethodError: method not found: 'which'
Receiver: Instance of 'MouseEventImpl'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      JSObject.noSuchMethod.throwError (dart:js:1171)
#3      JSObject.noSuchMethod (dart:js:1182)
#4      Sortable.init.<anonymous closure>.<anonymous closure> (package:bwu_datagrid/effects/sortable.dart:138:15)
  (anonymous function)	
`

looks like MouseEvent."which" was changed to "button".

**Comment by zoechi** [comment]
What bwu_datagrid version are you using? I think I changed that a while ago and I couldn't find a single `which` in the source code.

**Comment by andrey-zakharov** [comment]
In our project we are using Polymer 0.5, and we cannot upgrade to 1.0 as it would cost a lot of time.
So I'm using bwu_datagrid for 0.5 - pub get gives me 0.0.24.

**Comment by zoechi** [comment]
I see. I only did that change in the Polymer1 branch. It won't be much work to do that in the master branch as well. I'll have a look next week.

**Comment by zoechi** [comment]
Sorry, I don't know when I'll be able to do this. What about a PR?
