### ISSUE TITLE
IE 11 doesn't like style in shadowroot

### ISSUE THREAD

**Issue by bitcasst** [bwu-dart/bwu_datagrid#55]
The grid isn't able to fetch the proper style for the column cells in IE 11.
If we change this line <code>this.shadowRoot.append(_style);</code> to <code>dom.document.head.append(_style);</code> it works.

filename: bwu_datagrid.dart
line 1067 to ...
<code>
  void _createCssRules() {
    _style = new dom.StyleElement();
  //dom.document.head.append(_style);
    this.shadowRoot.append(_style);
...
}
</code>

to reproduce the issue try running  autotooltips.html example in IE 11.

**Comment by zoechi** [comment]
Closing this as stale. The grid was ported to Polymer 1 where lots of things are different.
