### ISSUE TITLE
Sort indicator not shown in Firefox

### ISSUE THREAD

**Issue by zoechi** [bwu-dart/bwu_datagrid#88]
http://localhost:8080/e13_get_item_sorting.html

**Comment by tonosama-atlacatl** [comment]
I ran into the same issue, and figured out that the icon indicator is present, but off to the bottom right, beyond the space taken by the column header.

Here is how I fixed it on my theme file:
```
.bwu-datagrid-sort-indicator {
                display: inline-block;
                width: 16px;
                height: 16px;
                margin-left: 4px;
                margin-top: 3px;
                float: right;
                -moz-margin-start: -18px; /* <<<<<<<<  */
            }
```
Where "-moz-maring-start" needs to be offseted according to the icon's height. In my case, my icons are 16px x 16px with a 3px top margin. 

The beauty of this temp solution is that it doesn't conflict with other browsers. I'm open to any other suggestions if you find a problem with this solution.

**Comment by zoechi** [comment]
I made an attempt but run into https://github.com/Polymer/polymer/issues/3690
I switched styling to a theme style-module instead of using CSS mixins because there are several selectors that can be combined in several ways which is too cumbersome using mixins and CSS variables.

At least the sort indicator is now shown, but to the right of the name instead of the left.
I'll publish an updated version soon.

**Comment by tonosama-atlacatl** [comment]
Yeah, the indicator on the right it's for my own implementation. Just change the "float:right" to "float:left".

**Comment by zoechi** [comment]
The indicator right is the default behavior because the elements are added in that order to the DOM. Some applied styles made it show to the left. 
The problem is that with the current styling implementation (that I implemented with the last update), it is not possible to change that in Firefox because of the bug linked above.

**Comment by zoechi** [comment]
I'm closing it because it is now shown. 
The custom styling possibilities are currently limited because of a Polymer issue. This is tracked by #145
